# Generated by Django 5.2 on 2025-05-03 10:57

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_customuser_address_customuser_city_customuser_cnic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=fernet_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cnic',
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cnic_expiry_date',
            field=fernet_fields.fields.EncryptedDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cnic_issue_date',
            field=fernet_fields.fields.EncryptedDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=128, null=True),
        ),
    ]
