# Generated by Django 5.2 on 2025-05-18 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_transaction_currency_transaction_fraud_probability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='fraud_probability',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField()),
                ('prediction', models.CharField(max_length=20)),
                ('fraud_probability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
