# Generated by Django 5.2 on 2025-05-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_transaction_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='fraud_score',
        ),
    ]
