apiVersion: v1
kind: Service
metadata:
  name: securepay-service
  namespace: securepay
spec:
  selector:
    app: securepay-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
